name: controlroom
dependencies:
  - python=3.6
  - cryptography
  - pip:
      - crossbar[all]
      - git+https://github.com/H-Plus-Time/newport-xps-q8.git
      - git+https://gitlab.com/weinshec/pyAPT.git
      - pyepics
